Repository emberjs/ember-inspector, pull requests merged in 2019-06, with the labels that each got.

#980 Fix hover colors of selected component
  app/styles/component_tree.scss
Labels: bug

#981 Increase size of click area of component tree disclosure triangle
  app/styles/component_tree.scss
  public/assets/svg/disclosure-triangle.svg
Labels: enhancement

#983 Drop support for Ember versions < 3.4.0 in master
  package.json
Labels: enhancement

#941 Remove View Tree
  app/components/view-item.js
  app/controllers/view-tree.js
  app/router.js
  app/routes/component-tree.js
  app/routes/view-tree.js
  app/schemas/view-tree.js
  app/templates/components/side-nav.hbs
  app/templates/components/view-item.hbs
  app/templates/nav.hbs
  app/templates/view-tree-toolbar.hbs
  app/templates/view-tree.hbs
  public/assets/svg/nav-view-tree.svg
  tests/acceptance/view-tree-test.js
Labels: enhancement, octane

#984 Highlight children of selected component
  app/components/component-tree-item.js
  app/controllers/component-tree.js
  app/helpers/component-has-element.js
  app/helpers/component-indentation.js
  app/helpers/component-parent-selected.js
  app/styles/component_tree.scss
  app/templates/component-tree.hbs
  app/templates/components/component-tree-item.hbs
Labels: enhancement

#990 Remove glimmer 2 checks
  ember_debug/view-debug.js
Labels: enhancement

#992 Component Tree: Angle Brackets and Classified Names
  app/helpers/classify.js
  app/helpers/console.js
  app/styles/component_tree.scss
  app/templates/components/component-tree-item.hbs
  tests/acceptance/component-tree-test.js
Labels: enhancement, octane
