Repository emberjs/ember-inspector, pull requests merged in 2020-05, with the labels that each got.

#1184 Remove moment, bump deps
  package.json
  yarn.lock
Labels: dependencies

#1202 Ensure renderDebug is properly unregistered.
  ember_debug/render-debug.js
  tests/ember_debug/container-debug-test.js
  tests/ember_debug/deprecation-debug-test.js
  tests/ember_debug/ember-debug-test.js
  tests/ember_debug/object-inspector-test.js
  tests/ember_debug/promise-debug-test.js
  tests/ember_debug/render-debug-test.js
  tests/ember_debug/route-debug-test.js
  tests/ember_debug/view-debug-test.js
  tests/test-helper.js
Labels: bug

#1203 Reset internal test helper state for EmberDebug tests.
  tests/helpers/setup-destroy-ei-app.js
  tests/integration/components/basic-test.js
Labels: internal

#1205 Remove private API usage to set moduleName in view debug tests.
  tests/ember_debug/view-debug-test.js
Labels: internal

#1204 Introduce `setupEmberDebugTest` test helper.
  tests/ember_debug/container-debug-test.js
  tests/ember_debug/deprecation-debug-test.js
  tests/ember_debug/ember-debug-test.js
  tests/ember_debug/object-inspector-test.js
  tests/ember_debug/profile-manager-test.js
  tests/ember_debug/profile-node-test.js
  tests/ember_debug/promise-assembler-test.js
  tests/ember_debug/promise-debug-test.js
  tests/ember_debug/render-debug-test.js
  tests/ember_debug/route-debug-test.js
  tests/ember_debug/view-debug-test.js
  tests/helpers/setup-destroy-ei-app.js
  tests/helpers/setup-ember-debug-test.js
  tests/integration/components/foo-test.js
  tests/test-helper.js
Labels: internal

#1193 Fix string arguments in component tree to render only one pair of double quotes fixes #1190
  app/components/component-tree-arg.js
  tests/integration/components/component-tree-arg-test.js
Labels: bug

#1215 Refactor `scripts/` to use more modern Node idioms.
  .eslintignore
  .eslintrc.js
  package.json
  scripts/download-panes.js
  scripts/upload-panes.js
  yarn.lock
Labels: internal

#1227 fix get class name
  ember_debug/object-inspector.js
Labels: bug
