Repository emberjs/ember-inspector, pull requests merged in 2020-08, with the labels that each got.

#1299 Ensure `valueForTag` is passed an actual `Tag`
  ember_debug/object-inspector.js
Labels: bug

#1273 Collapsible Navigation
  app/components/app-picker.hbs
  app/components/side-nav.hbs
  app/components/side-nav.js
  app/controllers/application.js
  app/helpers/match.js
  app/styles/dropdown.scss
  app/styles/utils.scss
  app/templates/application.hbs
  lib/ui/addon/styles/_nav.scss
  lib/ui/addon/styles/_object-inspector-toggle.scss
  lib/ui/addon/styles/_sidebar-toggle.scss
  lib/ui/addon/styles/_split.scss
  lib/ui/addon/styles/addon.scss
  public/assets/svg/dropdown-arrow.svg
  public/assets/svg/e-logo.svg
  public/assets/svg/ellipsis.svg
  public/assets/svg/nav-bug.svg
  public/assets/svg/nav-container.svg
  public/assets/svg/sidebar-toggle.svg
  tests/unit/match-test.js
  yarn.lock
Labels: enhancement

#1309 Fix some tests
  package.json
  tests/ember_debug/object-inspector-test.js
  yarn.lock
Labels: internal
