Repository emberjs/ember-inspector, pull requests merged in 2021-11, with the labels that each got.

#1760 Don't rely on Ember.EmberInspectorDebugger
  app/services/adapters/basic.js
  ember_debug/vendor/startup-wrapper.js
Labels: bug

#1771 remove port mixin
  ember_debug/container-debug.js
  ember_debug/data-debug.js
  ember_debug/debug-port.js
  ember_debug/deprecation-debug.js
  ember_debug/general-debug.js
  ember_debug/object-inspector.js
  ember_debug/promise-debug.js
  ember_debug/render-debug.js
  ember_debug/route-debug.js
  ember_debug/view-debug.js
Labels: internal

#1803 Replace ember-did-resize-modifier with ember-on-resize-modifier
  app/controllers/application.js
  app/modifiers/did-resize.js
  app/templates/application.hbs
  package.json
  yarn.lock
Labels: bug

#1804 Try to fix owner errors
  app/controllers/application.js
Labels: internal

#1821 docs(readme): change order of installation hints
  README.md
Labels: documentation
