Repository emberjs/ember-inspector, pull requests merged in 2021-05, with the labels that each got.

#1577 Add app config tab
  app/controllers/app-config.js
  app/router.js
  app/routes/app-config.js
  app/templates/app-config.hbs
  app/templates/info.hbs
  ember_debug/general-debug.js
  tests/acceptance/info-test.js
Labels: enhancement

#1590 Fix no-invalid-interactive
  .template-lintrc.js
  app/components/component-tree-item.hbs
  app/components/deprecation-item.hbs
  app/components/object-inspector/properties-grouped.hbs
  app/components/object-inspector/property.hbs
  app/components/promise-item.hbs
  app/components/route-cell-objects.hbs
  app/components/scroll-container.js
  app/templates/container-type.hbs
  ember_debug/libs/source-map.js
  ember_debug/utils/type-check.js
  lib/ui/addon/components/drag-handle.hbs
  package.json
  yarn.lock
Labels: internal

#1591 Fix some template lint issues
  .template-lintrc.js
  app/components/app-picker.hbs
  app/components/deprecation-item.hbs
  app/components/list-cell.hbs
  app/components/object-inspector.hbs
  app/components/side-nav.hbs
  app/templates/application.hbs
  app/templates/deprecations-toolbar.hbs
  app/templates/model-types-toolbar.hbs
  app/templates/promise-tree-toolbar.hbs
  app/templates/route-tree-toolbar.hbs
  lib/ui/addon/components/error-page.hbs
  lib/ui/addon/components/toolbar-search-field.hbs
  tests/acceptance/data-test.js
Labels: internal

#1601 Ensure vendored loader does not cache missing modules.
  ember_debug/vendor/loader.js
Labels: bug
