Repository emberjs/ember-inspector, pull requests merged in 2022-04, with the labels that each got.

#1959 component-tree: make left/right arrow nav in certain conditions (fixes #1537)
  app/controllers/component-tree.js
  tests/acceptance/component-tree-test.js
Labels: enhancement

#1972 properties-base, properties-grouped, properties-all: octane/glimmer upgrade
  app/components/object-inspector/properties-all.js
  app/components/object-inspector/properties-base.js
  app/components/object-inspector/properties-grouped.js
Labels: internal

#1975 list: fixup dot access for run.bind deprecation
  app/components/list.js
Labels: internal

#1974 deprecations: fix instances of routing-transition-methods
  app/routes/application.js
  app/routes/container-type.js
  app/routes/data/index.js
  app/routes/info-index.js
  app/routes/launch.js
  app/routes/model-type.js
  config/deprecation-workflow.js
Labels: internal

#1940 Remove support for the TargetActionSupport mixin
  ember_debug/object-inspector.js
Labels: bug

#1991 object-inspector-test: fix legacy-attribute-arguments issue
  tests/ember_debug/object-inspector-test.js
Labels: internal
