Repository emberjs/ember-inspector, pull requests merged in 2022-08, with the labels that each got.

#2040 do not close the object inspector
  ember_debug/libs/view-inspection.js
Labels: enhancement

#2101 Download panes from GitHub instead of S3
  scripts/download-panes.js
Labels: internal

#2103 Remove automated uploads
  README.md
  gulpfile.js
  package.json
  scripts/upload-panes.js
Labels: internal

#2100 Silence Ember.global deprecation messages when consumers use 3.28 with `throwOnUnhandled: true`
  app/services/adapters/web-extension.js
Labels: bug

#2108 fix ember inspector not loading
  app/services/adapters/web-extension.js
Labels: bug

#2122 Convert some components to glimmer
  app/components/object-inspector/accordion.js
  app/components/object-inspector/sort-properties.js
  app/components/promise-item.js
  app/components/route-cell-name.js
Labels: internal

#2127 Add back del
  package.json
  yarn.lock
Labels: internal

#2128 Target Ember 3.16+ for main branch
  .github/workflows/build.yml
  config/ember-try.js
  package.json
Labels: internal

#2126 Refactor List to glimmer, remove lifecycle hooks
  .eslintrc.js
  .github_changelog_generator
  CHANGELOG.md
  HISTORY.md
  app/components/list-content.hbs
  app/components/list-content.js
  app/components/list.hbs
  app/components/list.js
  app/components/scroll-container.hbs
  app/components/scroll-container.js
  config/deprecation-workflow.js
  lib/ui/addon/components/drag-handle.js
  package.json
  yarn.lock
Labels: internal

#2133 Update all master refs to main
  .github/workflows/build.yml
  README.md
  app/routes/whats-new.js
  tests/acceptance/whats-new-test.js
Labels: internal
