Repository emberjs/ember-inspector, pull requests merged in 2023-11, with the labels that each got.

#2487 [container debug] fix missing message handling
  ember_debug/container-debug.js
Labels: bug

#2460 use word-wrap and add line break controls
  ember_debug/libs/view-inspection.js
  tests/ember_debug/view-debug-test.js
Labels: enhancement

#2494 Update node and pnpm versions
  .github/workflows/build.yml
  .tool-versions
  package.json
Labels: internal

#2495 switch to source-map-js
  ember-cli-build.js
  ember_debug/libs/source-map.js
  ember_debug/utils/type-check.js
  package.json
  pnpm-lock.yaml
Labels: bug

#2499 fix inspector not showing up in certain cases
  package.json
  pnpm-lock.yaml
  public/assets/images/icon128_grey.png
  public/assets/images/icon19_grey.png
  public/assets/images/icon38_grey.png
  public/assets/images/icon48_grey.png
  public/assets/images/icon_grey16.png
  skeletons/web-extension/background.js
  skeletons/web-extension/manifest.json
  tests/integration/injection-test.js
Labels: bug

#2503 fix inspecting ember data records
  ember_debug/data-debug.js
Labels: bug

#2501 correctly load scripts in chrome & firefox
  ember-cli-build.js
  skeletons/web-extension/boot.js
  skeletons/web-extension/manifest.json
  skeletons/web-extension/scripts/boot.js
Labels: bug

#2509 fix publish - remove volta
  .github/workflows/build.yml
Labels: internal

#2510 Remove custom id setting since it is in manifest
  .github/workflows/build.yml
Labels: internal

#2517 [firefox] set access permissions for all websites
  skeletons/web-extension/manifest.json
Labels: bug

#2505 fix lazy routes debug
  ember_debug/route-debug.js
  tests/ember_debug/route-debug-test.js
Labels: bug
