Repository emberjs/ember-inspector, pull requests merged in 2023-10, with the labels that each got.

#2477 fix missing errors when digging into props
  app/routes/application.js
Labels: internal

#2476 fix manifest
  app/services/adapters/web-extension.js
  ember-cli-build.js
  skeletons/web-extension/boot.js
  skeletons/web-extension/content-script.js
  skeletons/web-extension/manifest.json
  skeletons/web-extension/scripts/boot.js
Labels: bug

#2471 Update README.md with pnpm usage
  README.md
  RELEASE.md
  package.json
Labels: documentation

#2484 fix .get is not defined
  ember_debug/libs/promise-assembler.js
Labels: bug
