Repository emberjs/ember-inspector, pull requests merged in 2024-07, with the labels that each got.

#2582 skip failing test
  tests/ember_debug/object-inspector-test.js
Labels: internal

#2587 do not use prototype extension
  ember_debug/deprecation-debug.js
Labels: bug

#2591 Use Personal Access Token
  .github/workflows/publish.yml
Labels: internal

#2585 Use GH_PAT token to hopefully fix releases
  .github/workflows/publish.yml
Labels: internal

#2581 provide name for hbs template only components
  ember_debug/libs/render-tree.js
Labels: enhancement

#2595 fix boolean edit
  app/components/object-inspector/property.ts
  tests/acceptance/object-inspector-test.js
Labels: bug
