Repository emberjs/ember-inspector, pull requests merged in 2024-02, with the labels that each got.

#2547 fix render tree triggering when already destroyed
  ember_debug/utils/base-object.js
  ember_debug/view-debug.js
Labels: bug

#2549 improve in element support
  ember_debug/libs/render-tree.js
  tests/ember_debug/view-debug-test.js
  tests/index.html
Labels: enhancement

#2511 chore(deps): remove unused AWS SDK for JavaScript
  package.json
  pnpm-lock.yaml
Labels: internal
