Repository emberjs/ember-inspector, pull requests merged in 2025-06, with the labels that each got.

#2647 Remove unused file `trigger-port.js`
  tests/helpers/trigger-port.js
Labels: internal

#2626 docs: add precisions about running for development with bookmarklet
  README.md
Labels: documentation

#2628 require all ember modules in one place
  ember_debug/utils/ember.js
  ember_debug/utils/ember/debug.js
  ember_debug/utils/ember/instrumentation.js
  ember_debug/utils/ember/object/internals.js
  ember_debug/utils/ember/runloop.js
  ember_debug/utils/rsvp.js
Labels: internal

#2639 fix `whats new` not showing latest changes
  app/routes/whats-new.js
  tests/acceptance/whats-new-test.js
Labels: bug

#2656 fix local dev
  .github/workflows/build.yml
  package.json
Labels: internal

#2662 fix watch test script
  package.json
Labels: internal

#2655 implement show parents only (focus mode)
  app/components/component-tree-toolbar.hbs
  app/controllers/component-tree.js
  app/templates/component-tree.hbs
  public/assets/svg/focus-point-round.svg
  tests/acceptance/component-tree-test.js
Labels: enhancement
